// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetcoreNewWeb.Models;

namespace aspnetcoreNewWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190617083113_AddPhotoPathCol")]
    partial class AddPhotoPathCol
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("aspnetcoreNewWeb.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PhotoPath");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 3,
                            Email = "aboulmagd@live.com",
                            Name = "Mohamed aboulmagd"
                        },
                        new
                        {
                            Id = 2,
                            Department = 2,
                            Email = "Ahmed@Outlook.com",
                            Name = "Ahmed Hossam"
                        },
                        new
                        {
                            Id = 3,
                            Department = 1,
                            Email = "shadi@gmail.com",
                            Name = "shadi hussan"
                        },
                        new
                        {
                            Id = 4,
                            Department = 3,
                            Email = "Eman@gmail.com",
                            Name = "Eman Abdallah"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
